theme: jekyll-theme-slate
title: OpenGL yard Simulation
description: This page is about my team final project on creating an outdoor scenery using OpenGL. The scene contains 4 different 3D objects with 1 object that have a simple animation. The objects are: Bush, Grass Wall, Wooden Fence, and a small Windmill. This scene also has a simple plane with a grass texture, and also use a skybox of clear sky.
